### ISSUE TITLE
Wierd behaviour spotted

### ISSUE THREAD

**Issue by bompi88** [bompi88/aiprog#16]
Here is an example, these are four sequential moves performed by the agent. These are not valid moves.

<img src="https://cloud.githubusercontent.com/assets/3270628/10362416/d8154358-6dae-11e5-95e1-1a92a69eba63.jpg" width="200"/>

<img src="https://cloud.githubusercontent.com/assets/3270628/10362417/d83c54ca-6dae-11e5-936e-7e6888e6c07b.jpg" width="200"/>

<img src="https://cloud.githubusercontent.com/assets/3270628/10362419/d83d9bf0-6dae-11e5-9982-0d6c8b86d23a.jpg" width="200"/>

<img src="https://cloud.githubusercontent.com/assets/3270628/10362418/d83d09f6-6dae-11e5-8191-5791cd34b56d.jpg" width="200"/>

**Comment by krisvage** [comment]
Is ok
